version: 2.1
description: test circleci

 
jobs:
  tests:
    working_directory: ~/test_circleci
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest hello.py --alluredir=results

  allure:
    working_directory: ~/test_circleci
    docker:
      - image: frankescobar/allure-docker-service:latest
    steps:
      - run:
          name: allure
          command: allure --version
      - run:
          name: generate 
          command: allure generate ~/test_circleci/results -o reports | pwd
      - run: pwd
      - store_artifacts:
          path: ~/test_circleci/reports
          destination: ~/test_circleci/reports/allure-report
      - store_test_results:
          path: ~/test_circleci/reports

workflows:
  version: 2
  install-run-report:
    jobs:
      - tests
      - allure
