version: 2.1
description: test circleci
 
jobs:
  tests:
    working_directory: ~/test_circleci
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest hello.py --alluredir=results
      - run: sudo npm install -g allure-commandline
      - run: allure generate --clean

workflows:
  version: 2
  install-run-report:
    jobs:
      - tests