version: 2.1
description: test circleci

 
jobs:
  tests:
    working_directory: ~/test_circleci
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run: pwd
      - run: sudo apt install default-jre
      - run: java -version
      - run: sudo apt install nodejs
      - run: node -v
      - run: sudo apt install npm
      - run: npm -v
      - run: sudo npm install -g allure-commandline
      - run: allure --version
      - run: pip install -r requirements.txt
      - run: pytest hello.py --alluredir=results
      - run: allure generate results -o reports
      - run: pytest hello.py --junitxml=~/test_circleci/report.xml
      - store_artifacts:
          path: ~/test_circleci/reports
          destination: allure-report
      - store_test_results:
          path: ~/test_circleci/report.xml

workflows:
  version: 2
  install-run-report:
    jobs:
      - tests
