version: 2.1
description: test circleci
orbs:
  allure: ayte/allure@0.1.3
      
jobs:
  example-job:
    working_directory: ~/test_circleci
    docker:
      - image: circleci/python:3.9.7
    steps:
      - allure/install:
          version: '2.15.0' 
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest hello.py --alluredir=results/10-11
      - run: allure serve results/10-11

workflows:
  example-workflows:
    jobs:
      - example-job