version: 2.1
description: test circleci
jobs:
  build:
    working_directory: ~/test_circleci
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest hello.py -vs
