version: 2.1
description: test circleci
orbs:
  allure: ayte/allure@0.1.3
      
jobs:
  install:
    docker:
      - image: cimg/openjdk:14.0
    steps:
      - checkout
      - run: java --version
      - allure/install:
          version: '2.13.1'
      - run: allure --version
  
  run-tests:
    working_directory: ~/test_circleci
    docker:
      - image: circleci/python:3.9.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest hello.py --alluredir=results

  report-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - allure/report:
          results-path: ~/test_circleci/results 
          target-path: ~/test_circleci/reports 
          artifact-path: ~/test_circleci/artifacts


workflows:
  version: 2
  install-run-report:
    jobs:
      - install:
          name: install
      - run-tests:
          name: run-tests
          requires:
            - install
      - report-tests:
          name: report-tests
          requires:
            - run-tests