version: 2.1
description: test circleci
orbs:
  allure: ayte/allure@0.1.3
      
jobs:
  run-tests:
    working_directory: ~/test_circleci
    docker:
      - image: circleci/python:3.9.7
      - image: cimg/openjdk:14.0
      - image: cimg/base:stable
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest hello.py --alluredir=results
      - run: java --version
      - allure/install:
          version: '2.13.1'
      - run: allure --version
      - allure/report:
          results-path: ~/test_circleci/results 
          target-path: ~/test_circleci/reports 
          artifact-path: ~/test_circleci/artifacts

workflows:
  version: 2
  install-run-report:
    jobs:
      - run-tests